import type { Metadata } from "next";
import { Inter } from "@next/font/google";
import "../styles/app.scss";

// Configure the Inter font
const inter = Inter({
  subsets: ["latin"], // Use Latin subset
  variable: "--font-inter", // Optional: CSS variable for global use
  weight: ["400", "700"], // Specify font weights needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* Apply the Inter font using its className */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
